// screens.dart

export 'package:Vincere/component/header.dart';
export 'package:Vincere/page_nutrition/screen_food_info.dart';
export 'package:Vincere/component/screen_loading.dart';
export 'package:Vincere/page_account/screen_login.dart';
export 'package:Vincere/page_nutrition/screen_my_nutri.dart';
export 'package:Vincere/page_notice/screen_qna_list.dart';
export 'package:Vincere/page_notice/screen_qna_view.dart';
export 'package:Vincere/page_notice/screen_regist_qna.dart';
export 'package:Vincere/page_account/screen_singup.dart';
export 'package:Vincere/page_my_health/screen_his_health.dart';
export 'package:Vincere/component/custom_drawer.dart';
export 'package:Vincere/page_home/screen_home.dart';
import 'package:Vincere/component/custom_drawer.dart';
import 'package:Vincere/component/header.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:Vincere/provider_models.dart';
import 'package:Vincere/page_workout/page_select_muscle.dart';
